import { useState, useEffect, useCallback } from "react";
import {
  AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell
} from "recharts";
import { money } from "../lib/formatters";

interface PnlData {
  connected: boolean;
  period_days: number;
  revenue: number;
  ad_spend: number;
  fba_fees: number;
  cogs: number;
  net_profit: number;
  acos_overall: number;
  roas: number;
  units_sold: number;
  daily: Array<{ date: string; revenue: number; spend: number; profit: number }>;
  by_asin: Array<{ asin: string; name: string; revenue: number; acos: number; units: number; profit: number }>;
  inventory_alerts: Array<{ asin: string; name: string; days_of_supply: number; severity: string }>;
}

type SortKey = "name" | "revenue" | "acos" | "units" | "profit";
type SortDir = "asc" | "desc";

const PERIOD_OPTIONS = [7, 14, 30, 90] as const;

function acosColor(acos: number): string {
  if (acos <= 20) return "#10b981";
  if (acos <= 30) return "#f59e0b";
  return "#ef4444";
}

function severityColor(severity: string): string {
  if (severity === "critical") return "#ef4444";
  if (severity === "warning") return "#f59e0b";
  return "#10b981";
}

function copyReorderTemplate(alert: { asin: string; name: string; days_of_supply: number; severity: string }) {
  const msg = `REORDER REQUIRED — ${alert.severity.toUpperCase()}\n\nProduct: ${alert.name}\nASIN: ${alert.asin}\nDays of Supply Remaining: ${alert.days_of_supply}\n\nPlease initiate reorder immediately to prevent stockout.\n\nGenerated by AZ Finds Command Center`;
  navigator.clipboard.writeText(msg).then(() => {
    // notification handled by caller context
  }).catch(() => {});
}

export function PnlWarRoom() {
  const [days, setDays] = useState<number>(30);
  const [data, setData] = useState<PnlData | null>(null);
  const [loading, setLoading] = useState(true);
  const [sortKey, setSortKey] = useState<SortKey>("profit");
  const [sortDir, setSortDir] = useState<SortDir>("desc");
  const [cash, setCash] = useState<number>(() => {
    const stored = localStorage.getItem("az_cash_balance");
    return stored ? parseFloat(stored) : 10000;
  });
  const [copyMsg, setCopyMsg] = useState<string>("");

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const r = await fetch(`/api/pnl?days=${days}`);
      if (r.ok) {
        setData(await r.json());
      } else {
        // Fallback mock data
        setData({
          connected: false, period_days: days,
          revenue: 18420, ad_spend: 2640, fba_fees: 3100, cogs: 6800, net_profit: 5880,
          acos_overall: 14.3, roas: 6.97, units_sold: 312,
          daily: Array.from({ length: days }, (_, i) => ({
            date: new Date(Date.now() - (days - i) * 86400000).toLocaleDateString("en-US", { month: "short", day: "numeric" }),
            revenue: 400 + Math.random() * 400,
            spend: 60 + Math.random() * 80,
            profit: 120 + Math.random() * 200,
          })),
          by_asin: [
            { asin: "B001", name: "Premium Widget", revenue: 8200, acos: 12.1, units: 142, profit: 2800 },
            { asin: "B002", name: "Eco Organizer", revenue: 5400, acos: 18.4, units: 98, profit: 1940 },
            { asin: "B003", name: "Travel Kit", revenue: 4820, acos: 24.7, units: 72, profit: 1140 },
          ],
          inventory_alerts: [
            { asin: "B001", name: "Premium Widget", days_of_supply: 8, severity: "critical" },
            { asin: "B003", name: "Travel Kit", days_of_supply: 18, severity: "warning" },
          ],
        });
      }
    } catch {
      setData(null);
    } finally {
      setLoading(false);
    }
  }, [days]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const handleCashChange = (val: number) => {
    setCash(val);
    localStorage.setItem("az_cash_balance", String(val));
  };

  const handleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortDir(d => d === "asc" ? "desc" : "asc");
    } else {
      setSortKey(key);
      setSortDir("desc");
    }
  };

  const sortedAsins = data ? [...data.by_asin].sort((a, b) => {
    const aVal = a[sortKey] as number | string;
    const bVal = b[sortKey] as number | string;
    const cmp = typeof aVal === "string" ? aVal.localeCompare(bVal as string) : (aVal as number) - (bVal as number);
    return sortDir === "desc" ? -cmp : cmp;
  }) : [];

  if (loading) {
    return (
      <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: 300, color: "var(--u-muted)", fontSize: 14 }}>
        Loading P&L data...
      </div>
    );
  }

  if (!data) {
    return (
      <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: 300, color: "var(--u-muted)", fontSize: 14 }}>
        Failed to load P&L data.
      </div>
    );
  }

  const weeklyBurn = (data.cogs + data.ad_spend) / (days / 7);
  const runway = weeklyBurn > 0 ? cash / weeklyBurn : 99;
  const runwayColor = runway >= 12 ? "#10b981" : runway >= 6 ? "#f59e0b" : "#ef4444";
  const runwayPct = Math.min(100, (runway / 20) * 100);

  const colHeader = (label: string, key: SortKey) => (
    <th
      onClick={() => handleSort(key)}
      style={{ padding: "10px 12px", textAlign: "left", fontSize: 11, fontWeight: 600, color: "var(--u-muted)", letterSpacing: "0.06em", textTransform: "uppercase", cursor: "pointer", userSelect: "none", whiteSpace: "nowrap" }}
    >
      {label} {sortKey === key ? (sortDir === "desc" ? "↓" : "↑") : ""}
    </th>
  );

  return (
    <div style={{ padding: "0 0 32px" }}>
      {/* Period selector */}
      <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 20, gap: 6 }}>
        {PERIOD_OPTIONS.map(p => (
          <button
            key={p}
            onClick={() => setDays(p)}
            style={{
              padding: "6px 14px", borderRadius: 8, border: "1px solid",
              borderColor: days === p ? "var(--u-neon-blue)" : "var(--u-border)",
              background: days === p ? "rgba(59,130,246,0.15)" : "transparent",
              color: days === p ? "var(--u-neon-blue)" : "var(--u-muted)",
              fontSize: 13, fontWeight: 600, cursor: "pointer",
            }}
          >{p}d</button>
        ))}
      </div>

      {/* Not-connected banner */}
      {!data.connected && (
        <div style={{
          background: "rgba(245,158,11,0.1)", border: "1px solid rgba(245,158,11,0.3)",
          borderRadius: 10, padding: "10px 16px", marginBottom: 20, fontSize: 13,
          color: "#fcd34d", display: "flex", alignItems: "center", gap: 8,
        }}>
          <span>⚠</span>
          Showing estimate-level data — connect SP-API for live figures
        </div>
      )}

      {/* KPI Hero Cards */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 12, marginBottom: 24 }}>
        {[
          { label: "Revenue", value: `$${money(data.revenue).slice(1)}`, color: "var(--u-neon-gold)" },
          { label: "Net Profit", value: `$${money(data.net_profit).slice(1)}`, color: data.net_profit >= 0 ? "var(--u-neon-green)" : "#ef4444" },
          { label: "ACOS", value: `${data.acos_overall.toFixed(1)}%`, color: acosColor(data.acos_overall) },
          { label: "Units Sold", value: data.units_sold.toLocaleString(), color: "var(--u-neon-blue)" },
          { label: "ROAS", value: `${data.roas.toFixed(2)}x`, color: "var(--u-neon-cyan)" },
        ].map(card => (
          <div key={card.label} style={{
            background: "var(--u-card)", border: "1px solid var(--u-border)", borderRadius: 16,
            padding: "20px", position: "relative", overflow: "hidden",
            borderTop: `3px solid ${card.color}`,
          }}>
            <div style={{ fontSize: 11, color: "var(--u-muted)", fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 8 }}>{card.label}</div>
            <div style={{ fontSize: 26, fontWeight: 800, color: card.color, letterSpacing: "-0.02em" }}>{card.value}</div>
          </div>
        ))}
      </div>

      {/* Charts row */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 24 }}>
        <div style={{ background: "var(--u-card)", border: "1px solid var(--u-border)", borderRadius: 16, padding: "20px" }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: "var(--u-text)", marginBottom: 16 }}>Revenue vs Ad Spend</div>
          <ResponsiveContainer width="100%" height={220}>
            <AreaChart data={data.daily} margin={{ top: 4, right: 4, left: -20, bottom: 0 }}>
              <defs>
                <linearGradient id="revGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.4} />
                  <stop offset="95%" stopColor="#3b82f6" stopOpacity={0.02} />
                </linearGradient>
                <linearGradient id="spendGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#ec4899" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="#ec4899" stopOpacity={0.02} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(59,130,246,0.08)" />
              <XAxis dataKey="date" tick={{ fontSize: 10, fill: "#64748b" }} tickLine={false} axisLine={false} interval="preserveStartEnd" />
              <YAxis tick={{ fontSize: 10, fill: "#64748b" }} tickLine={false} axisLine={false} tickFormatter={v => `$${v}`} />
              <Tooltip contentStyle={{ background: "var(--u-elevated)", border: "1px solid var(--u-border)", borderRadius: 8, fontSize: 12 }} />
              <Area type="monotone" dataKey="revenue" name="Revenue" stroke="#3b82f6" fill="url(#revGrad)" strokeWidth={2} dot={false} />
              <Area type="monotone" dataKey="spend" name="Ad Spend" stroke="#ec4899" fill="url(#spendGrad)" strokeWidth={2} dot={false} />
            </AreaChart>
          </ResponsiveContainer>
        </div>

        <div style={{ background: "var(--u-card)", border: "1px solid var(--u-border)", borderRadius: 16, padding: "20px" }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: "var(--u-text)", marginBottom: 16 }}>Daily Net Profit</div>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={data.daily} margin={{ top: 4, right: 4, left: -20, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(59,130,246,0.08)" />
              <XAxis dataKey="date" tick={{ fontSize: 10, fill: "#64748b" }} tickLine={false} axisLine={false} interval="preserveStartEnd" />
              <YAxis tick={{ fontSize: 10, fill: "#64748b" }} tickLine={false} axisLine={false} tickFormatter={v => `$${v}`} />
              <Tooltip contentStyle={{ background: "var(--u-elevated)", border: "1px solid var(--u-border)", borderRadius: 8, fontSize: 12 }} />
              <Bar dataKey="profit" name="Net Profit" radius={[3, 3, 0, 0]}>
                {data.daily.map((entry, i) => (
                  <Cell key={i} fill={entry.profit >= 0 ? "#10b981" : "#ef4444"} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Bottom section */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 320px", gap: 16, marginBottom: 24 }}>
        {/* ASIN P&L Table */}
        <div style={{ background: "var(--u-card)", border: "1px solid var(--u-border)", borderRadius: 16, overflow: "hidden" }}>
          <div style={{ padding: "16px 20px 12px", borderBottom: "1px solid var(--u-border)" }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: "var(--u-text)" }}>ASIN P&L Breakdown</div>
          </div>
          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ borderBottom: "1px solid var(--u-border)" }}>
                  {colHeader("Name", "name")}
                  {colHeader("Revenue", "revenue")}
                  {colHeader("ACOS", "acos")}
                  {colHeader("Units", "units")}
                  {colHeader("Profit", "profit")}
                </tr>
              </thead>
              <tbody>
                {sortedAsins.map((row, i) => (
                  <tr key={row.asin} style={{ borderBottom: i < sortedAsins.length - 1 ? "1px solid var(--u-border)" : "none", transition: "background 0.15s" }}
                    onMouseEnter={e => { (e.currentTarget as HTMLTableRowElement).style.background = "var(--u-glass)"; }}
                    onMouseLeave={e => { (e.currentTarget as HTMLTableRowElement).style.background = "transparent"; }}>
                    <td style={{ padding: "12px 12px", fontSize: 13, color: "var(--u-text)", fontWeight: 500 }}>
                      <div>{row.name}</div>
                      <div style={{ fontSize: 11, color: "var(--u-muted)", marginTop: 2 }}>{row.asin}</div>
                    </td>
                    <td style={{ padding: "12px 12px", fontSize: 13, color: "var(--u-text)" }}>${money(row.revenue).slice(1)}</td>
                    <td style={{ padding: "12px 12px", fontSize: 13, fontWeight: 600, color: acosColor(row.acos) }}>{row.acos.toFixed(1)}%</td>
                    <td style={{ padding: "12px 12px", fontSize: 13, color: "var(--u-text)" }}>{row.units}</td>
                    <td style={{ padding: "12px 12px", fontSize: 13, fontWeight: 600, color: row.profit < 0 ? "#ef4444" : "var(--u-text)" }}>${money(row.profit).slice(1)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Inventory Alerts */}
        <div style={{ background: "var(--u-card)", border: "1px solid var(--u-border)", borderRadius: 16, overflow: "hidden" }}>
          <div style={{ padding: "16px 20px 12px", borderBottom: "1px solid var(--u-border)" }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: "var(--u-text)" }}>Inventory Status</div>
          </div>
          <div style={{ padding: "8px 0" }}>
            {data.inventory_alerts.length === 0 && (
              <div style={{ padding: "24px 20px", textAlign: "center", color: "var(--u-muted)", fontSize: 13 }}>All products well-stocked ✓</div>
            )}
            {data.inventory_alerts.map(alert => {
              const color = severityColor(alert.severity);
              return (
                <div key={alert.asin} style={{ padding: "12px 16px", borderLeft: `3px solid ${color}`, borderBottom: "1px solid var(--u-border)", marginBottom: 0 }}>
                  <div style={{ fontSize: 13, fontWeight: 600, color: "var(--u-text)", marginBottom: 4 }}>{alert.name}</div>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
                    <span style={{ fontSize: 11, fontWeight: 700, background: `${color}22`, color, borderRadius: 6, padding: "2px 8px" }}>
                      {alert.days_of_supply}d supply
                    </span>
                    <span style={{ fontSize: 11, color, fontWeight: 600, textTransform: "uppercase" }}>{alert.severity}</span>
                  </div>
                  {(alert.severity === "critical" || alert.severity === "warning") && (
                    <button
                      onClick={() => {
                        copyReorderTemplate(alert);
                        setCopyMsg(alert.asin);
                        setTimeout(() => setCopyMsg(""), 2000);
                      }}
                      style={{ fontSize: 11, padding: "5px 10px", background: color, color: "#fff", border: "none", borderRadius: 6, cursor: "pointer", fontWeight: 700 }}
                    >
                      {copyMsg === alert.asin ? "COPIED!" : "REORDER NOW"}
                    </button>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Cash Runway Calculator */}
      <div style={{ background: "var(--u-card)", border: "1px solid var(--u-border)", borderRadius: 16, padding: "20px" }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: "var(--u-text)", marginBottom: 16 }}>Cash Runway Calculator</div>
        <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 16, flexWrap: "wrap" }}>
          <div>
            <div style={{ fontSize: 11, color: "var(--u-muted)", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.06em" }}>Current Cash Balance</div>
            <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
              <span style={{ color: "var(--u-muted)", fontSize: 16, fontWeight: 600 }}>$</span>
              <input
                type="number"
                value={cash}
                onChange={e => handleCashChange(parseFloat(e.target.value) || 0)}
                style={{
                  background: "var(--u-elevated)", border: "1px solid var(--u-border)", color: "var(--u-text)",
                  borderRadius: 8, padding: "8px 12px", fontSize: 14, width: 140, outline: "none",
                }}
              />
            </div>
          </div>
          <div style={{ flex: 1, minWidth: 200 }}>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>
              <span style={{ fontSize: 11, color: "var(--u-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Runway</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: runwayColor }}>{runway > 99 ? "99+" : runway.toFixed(1)} weeks</span>
            </div>
            <div style={{ height: 8, background: "var(--u-elevated)", borderRadius: 4, overflow: "hidden" }}>
              <div style={{
                height: "100%", width: `${runwayPct}%`, borderRadius: 4,
                background: `linear-gradient(90deg, ${runwayColor}, ${runwayColor}aa)`,
                transition: "width 0.4s ease",
              }} />
            </div>
            <div style={{ fontSize: 12, color: "var(--u-muted)", marginTop: 8 }}>
              You can fund ~{runway > 99 ? "99+" : Math.floor(runway)} weeks of operations at current burn rate
              {" "}(weekly burn: ${money(weeklyBurn).slice(1)})
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
